[package]
name = "cargo-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.76"
gix = { version = "0.55", features = ["blocking-http-transport-curl"] }
serde_json = "1"
